import { ClickHouseUxSessionStore } from '@/lib/clickhouse/repositories/ClickHouseUxSessionStore';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Activity, MousePointer2, AlertCircle } from 'lucide-react';

// Mock function to decode hash to project ID
function getProjectFromHash(hash: string) {
    // Simple mock: assume hash IS the project ID for MVP
    return hash;
}

export default async function PublicDashboardPage({ params }: { params: { hash: string } }) {
    const projectId = getProjectFromHash(params.hash);
    const metrics = await ClickHouseUxSessionStore.getMetrics(projectId);

    return (
        <div className="container mx-auto p-8 space-y-8">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">Public Report: {projectId}</h1>
                    <p className="text-muted-foreground">Read-only view of project performance.</p>
                </div>
                <Badge variant="outline">Public View</Badge>
            </div>

            {/* Metrics Grid (Reused from UX Dashboard) */}
            <div className="grid gap-4 md:grid-cols-3">
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Success Rate</CardTitle>
                        <Activity className="h-4 w-4 text-green-500" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{metrics.successRate}%</div>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Avg Clicks</CardTitle>
                        <MousePointer2 className="h-4 w-4 text-blue-500" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{metrics.avgClicks}</div>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Friction Score</CardTitle>
                        <AlertCircle className="h-4 w-4 text-red-500" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{metrics.frictionScore}</div>
                    </CardContent>
                </Card>
            </div>

            <div className="text-center text-sm text-muted-foreground pt-8">
                Generated by ApexSEO Space
            </div>
        </div>
    );
}
