import { NextRequest, NextResponse } from 'next/server';
import { Connection, Client } from '@temporalio/client';

// Initialize Temporal Client (Singleton-ish pattern for Next.js)
let temporalClient: Client | undefined;

// Mock store for simulation mode
const SIMULATION_STORE: Record<string, { startTime: number, topic: string }> = {};

async function getTemporalClient() {
    if (temporalClient) return temporalClient;

    try {
        const connection = await Connection.connect({
            address: process.env.TEMPORAL_ADDRESS || 'localhost:7233',
            connectTimeout: 1000
        });
        temporalClient = new Client({
            connection,
            namespace: 'default',
        });
        return temporalClient;
    } catch (e) {
        console.warn("Could not connect to Temporal, falling back to simulation mode.");
        return null;
    }
}

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const { action, ...data } = body;
        const client = await getTemporalClient();

        // 1. Start Workflow
        if (action === 'start') {
            const { topic, userId, projectId, config } = data;
            const workflowId = `content-gen-${projectId}-${Date.now()}`;

            if (client) {
                await client.workflow.start('ContentGenerationWorkflow', {
                    taskQueue: 'seo-tasks-queue',
                    workflowId: workflowId,
                    args: [{ topic, userId, projectId, config }],
                });
            } else {
                // Simulation Mode
                SIMULATION_STORE[workflowId] = { startTime: Date.now(), topic };
            }

            return NextResponse.json({ workflowId });
        }

        // 2. Refine (Signal)
        if (action === 'refine') {
            const { workflowId, instructions } = data;
            if (client) {
                const handle = client.workflow.getHandle(workflowId);
                await handle.signal('refine', instructions);
            }
            return NextResponse.json({ success: true });
        }

        return NextResponse.json({ error: 'Invalid action' }, { status: 400 });

    } catch (error: any) {
        console.error('Temporal API Error:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}

export async function GET(req: NextRequest) {
    try {
        const { searchParams } = new URL(req.url);
        const workflowId = searchParams.get('workflowId');

        if (!workflowId) {
            return NextResponse.json({ error: 'Missing workflowId' }, { status: 400 });
        }

        const client = await getTemporalClient();

        if (client) {
            try {
                const handle = client.workflow.getHandle(workflowId);
                const description = await handle.describe();
                const status = description.status.name;

                let result = null;
                if (status === 'COMPLETED') {
                    result = await handle.result();
                }

                return NextResponse.json({
                    status,
                    result,
                    isRunning: status === 'RUNNING'
                });
            } catch (e) {
                // Fallback to simulation if workflow not found in Temporal (maybe it was a sim ID)
            }
        }

        // Simulation Logic
        const sim = SIMULATION_STORE[workflowId];
        if (!sim) {
            return NextResponse.json({ error: 'Workflow not found' }, { status: 404 });
        }

        const elapsed = Date.now() - sim.startTime;
        let status = 'RUNNING';
        let result = null;
        let progress = "Starting...";

        if (elapsed < 2000) progress = "Gathering Data (Keywords, SERP)...";
        else if (elapsed < 4000) progress = "Designing Architecture...";
        else if (elapsed < 6000) progress = "Drafting Content with LLM...";
        else if (elapsed < 8000) progress = "Finalizing...";
        else {
            status = 'COMPLETED';
            result = {
                content: `<h1>${sim.topic}</h1><p>This is a simulated draft generated for ${sim.topic}. In a real environment, this would be generated by an LLM based on deep research.</p><h2>Key Takeaways</h2><ul><li>Point 1</li><li>Point 2</li></ul>`,
                metadata: { wordCount: 500, readingTime: 3 },
                eeatScore: 92,
                projectId: 'project-1',
                targetKeyword: sim.topic
            };
        }

        return NextResponse.json({
            status,
            result,
            progress, // Custom field for simulation feedback
            isRunning: status === 'RUNNING'
        });

    } catch (error: any) {
        console.error('Temporal Query Error:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
